# Copyright (c) 2015 to Jason van Zyl
# All rights reserved. This program and the accompanying materials                                                                                                                                          
# are made available under the terms of the Eclipse Public License v1.0                                                                                                                                     
# which accompanies this distribution, and is available at                                                                                                                                                  
# http://www.eclipse.org/legal/epl-v10.html   
#
# This generates everything needed to create a distributions
#
# https://git.eclipse.org/c/epp/org.eclipse.epp.packages.git/tree/packages/org.eclipse.epp.package.rcp.feature/feature.xml

groupId: "io.tesla.ide"
pluginId: "io.tesla.ide"
featureId: "io.tesla.ide.feature"
productId: "io.tesla.ide.product"
productName: VizIDE
introImage: intro-takari.png
tychoVersion: 0.26.0
mavenVersion: "1.0.0-SNAPSHOT"
version: "1.0.0.qualifier"
cssTheme: io.takari.dark.theme
applicationId: io.tesla.ide.application
applicationClass: io.tesla.ide.TakariIde
   
modules:
 - io.tesla.ide
 - io.tesla.ide.feature
 - io.tesla.ide.product

featurePlugins:
 - io.tesla.ide

featureSets: 
 -
  eclipse:
   repo: http://download.eclipse.org/eclipse/updates/4.7milestones/
   features:
    - id: org.eclipse.platform
    - id: org.eclipse.rcp
    - id: org.eclipse.jdt
    - id: org.eclipse.equinox.p2.user.ui
    - id: org.eclipse.egit
    - id: io.tesla.ide.feature
    - id: org.eclipse.m2e.feature
 -
  docker:
   features:
    - id: org.eclipse.linuxtools.docker.feature
 -
  m2e:
   features:
    - id: org.eclipse.m2e.feature
 -
#  marketplace:
#   repo: http://download.eclipse.org/mpc/nightly/
#   features:
#    - id: org.eclipse.epp.mpc
# -
  onboarding:
   repo: https://otto.takari.io/content/sites/m2e.extras/m2eclipse-onboarding/0.0.1/N/0.0.1.201406270046/
   features:
    - id: io.tesla.m2e.onboarding.feature
 -
  yedit:
   repo: http://dadacoalition.org/yedit/
   features:
    - id: org.dadacoalition.yedit.feature
 -
  formatter-plugin:
   repo: http://velo.github.io/maven-formatter-plugin/p2/LATEST/
   features:
    - id: com.marvinformatics.formatter.feature
 -
  grep-console:
   repo: http://eclipse.schedenig.name
   features:
    - id: name.schedenig.eclipse.grepconsole
 -
  code-coverage:
   repo: http://update.eclemma.org/
   features:
    - id: com.mountainminds.eclemma.feature
 -
  jboss-tools:
   repo: http://download.jboss.org/jbosstools/neon/development/updates/
   features:
    - id: org.jboss.tools.livereload.feature
    - id: org.jboss.ide.eclipse.as.feature
    - id: org.jboss.tools.maven.sourcelookup.feature
 -
  jetty-launcher:
   repo: http://eclipse-jetty.github.io/update/
   features:
    - id: net.sourceforge.eclipsejetty.feature
 -
  mutation-tests:
   repo: http://eclipse.pitest.org/release
   features:
    - id: org.pitest.pitclipse.feature
 -
  m2eclipse-buildhelper:
   repo: http://repo1.maven.org/maven2/.m2e/connectors/m2eclipse-buildhelper/0.15.0/N/0.15.0.201207090124/
   features:
    - id: org.sonatype.m2e.buildhelper.feature
 -
  m2eclipse-wtp:
   features:
    - id: org.eclipse.m2e.wtp.feature
 -
  m2eclipse-code-quality:
   repo: http://m2e-code-quality.github.com/m2e-code-quality/site/
   features:
    - id: com.basistech.m2e.code.quality.checkstyle.feature
 -
  json-edit:
   repo: https://bitbucket.org/denmiroch/jsontools/raw/ae2e9d683249ef989d940b441e00b74df729164c/JsonSite/
   features:
    - id: org.sweetlemonade.eclipse.json.feature
 -
  csv-edit:
   repo: https://raw.githubusercontent.com/SegFaultError/CsvEdit/master/csvedit.update/
   features:
    - id: org.fhsolution.eclipse.feature.csvedit
 -
  typescript-edit:
   repo: http://eclipse-update.palantir.com/eclipse-typescript/
   features:
    - id: com.palantir.typescript.feature
 -
  m2e-apt:
   repo: http://download.jboss.org/jbosstools/updates/m2e-extensions/m2e-apt/
   features:
    - id: org.jboss.tools.maven.apt.feature
 -
  gradle:
   repo: http://download.eclipse.org/buildship/updates/e46/releases/2.x/
   features:
    - id: org.eclipse.buildship
 -
  tycho-configurator:
   repo: https://repository.takari.io/content/sites/m2e.extras/m2eclipse-tycho/0.9.0/N/LATEST/
   features:
    - id: org.sonatype.tycho.m2e.feature
 -
  jibx:
   repo: http://velo.github.io/jibx-eclipse/
   features:
    - id: org.jibx.eclipse.feature
# -
#  ajdt:
#   repo: http://download.eclipse.org/tools/ajdt/46/dev/update
#   features:
#    - id: org.eclipse.ajdt
 -
  takari:
   repo: https://download.takari.io/eclipse/takari-lifecycle/
   features:
    - id: io.takari.m2e.lifecycle.feature
 -
  mavendev:
   repo: http://ifedorenko.github.com/m2e-extras/
   features:
    - id: com.ifedorenko.m2e.sourcelookup.feature
    - id: com.ifedorenko.m2e.mavendev.feature
 -
  angularjs:
   repo: http://oss.opensagres.fr/angularjs-eclipse/1.1.0/
   features:
    - id: org.eclipse.wst.html.webresources.feature
    - id: angularjs-eclipse-feature
 -
  testng:
   repo: http://beust.com/eclipse/
   features:
    - id: org.testng.eclipse
    - id: org.testng.eclipse.maven.feature
 -
  m2e-maven-dependency-plugin:
   repo: http://ianbrandt.github.io/m2e-maven-dependency-plugin/0.0.4/
   features:
    - id: com.ianbrandt.tools.m2e.mdp.feature
 -
  java9:
   repo: http://download.eclipse.org/eclipse/updates/4.7-P-builds/
   features:
    - id: org.eclipse.jdt.java9patch
 -
  markdown-editor:
   repo: http://www.nodeclipse.org/updates/markdown/
   features:
    - id: markdown.editor.feature
 -
  markdown-preview:
   repo: https://raw.github.com/satyagraha/gfm_viewer/master/p2-composite/
   features:
    - id: code.satyagraha.gfm.viewer.feature
