# Copyright (c) 2015 to Jason van Zyl
# All rights reserved. This program and the accompanying materials                                                                                                                                          
# are made available under the terms of the Eclipse Public License v1.0                                                                                                                                     
# which accompanies this distribution, and is available at                                                                                                                                                  
# http://www.eclipse.org/legal/epl-v10.html   
#
# This generates everything needed to create a distributions
#
# https://git.eclipse.org/c/epp/org.eclipse.epp.packages.git/tree/packages/org.eclipse.epp.package.rcp.feature/feature.xml

groupId: "io.tesla.ide"
pluginId: "io.tesla.ide"
featureId: "io.tesla.ide.feature"
productId: "io.tesla.ide.product"
productName: VizIDE
introImage: intro-takari.png
tychoVersion: 0.26.0
mavenVersion: "1.0.0-SNAPSHOT"
version: "1.0.0.qualifier"
cssTheme: io.takari.dark.theme
applicationId: io.tesla.ide.application
applicationClass: io.tesla.ide.TakariIde
   
modules:
 - io.tesla.ide
 - io.tesla.ide.feature
 - io.tesla.ide.product

featurePlugins:
 - io.tesla.ide

featureSets: 
 -
  eclipse:
   repo: http://download.eclipse.org/releases/oxygen/
   features:
    - id: org.eclipse.platform
    - id: org.eclipse.equinox.p2.user.ui
    - id: org.eclipse.egit
    - id: io.tesla.ide.feature
    - id: org.eclipse.wst.jsdt.feature
 -
  markdown-editor:
   repo: http://www.nodeclipse.org/updates/markdown/
   features:
    - id: markdown.editor.feature
 -
  markdown-preview:
   repo: https://raw.github.com/satyagraha/gfm_viewer/master/p2-composite/
   features:
    - id: code.satyagraha.gfm.viewer.feature
 -
  editorconfig:
   repo: https://editorconfig-eclipse.github.io/repository
   features:
    - id: editorconfig-eclipse-feature
